language: php

php:
  - 5.6

before_script:
  - cp .env.travis .env
  - mysql -e 'create database homestead_test;'
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate
script:
  - vendor/bin/phpunit
deploy:
  provider: heroku
  api_key: fd0f0e37-2887-484e-a6e0-137cd952a816
  app: react-tutorial-hoanghoi
  run:
    - "php -r \"file_exists('.env') || copy('.env.example', '.env');\""
    - "php artisan key:generate"
    - "php artisan migrate --force"
